import typing
from typing import Any, Generic, TypeAlias, TypeVar, overload

import numpy as np

from ..type_hints import (
    NDArray1DDateTime64,
    NDArray1DFloat32,
    NDArray1DFloat64,
    NDArray1DInt64,
    NDArray1DTimeDelta64,
    NDArray1DUInt32,
    NDArray2DFloat32,
    NDArray2DFloat64,
    NDArray2DInt64,
    NDArray2DUInt64,
    Vector3Float32,
    Vector3Float64,
)
from . import geodetic
from .config import geometric, rtree, windowed

# Type alias for temporal coordinate arrays
TemporalArray: TypeAlias = NDArray1DDateTime64 | NDArray1DTimeDelta64

def bivariate(
    grid: GridHolder,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    config: geometric.Bivariate | windowed.Bivariate,
) -> NDArray1DFloat32 | NDArray1DFloat64: ...
def trivariate(
    grid: GridHolder,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64 | TemporalArray,
    config: geometric.Trivariate | windowed.Trivariate,
) -> NDArray1DFloat32 | NDArray1DFloat64: ...
def quadrivariate(
    grid: GridHolder,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64 | TemporalArray,
    u: NDArray1DFloat64,
    config: geometric.Quadrivariate | windowed.Quadrivariate,
) -> NDArray1DFloat32 | NDArray1DFloat64: ...

class Axis:
    def __init__(
        self,
        values,
        epsilon: float = ...,
        period: float | None = ...,
    ) -> None: ...
    def back(self) -> float: ...
    def find_index(self, *args, **kwargs): ...
    def find_indexes(self, *args, **kwargs): ...
    def flip(self, inplace: bool = ...) -> Axis: ...
    def front(self) -> float: ...
    @overload
    def increment(self) -> float: ...
    @overload
    def increment(self, step) -> Any: ...
    def is_ascending(self) -> bool: ...
    def is_regular(self) -> bool: ...
    def max_value(self) -> float: ...
    def min_value(self) -> float: ...
    def __copy__(self) -> Axis: ...
    def __eq__(self, other: object) -> bool: ...
    @overload
    def __getitem__(self, index: int) -> float: ...
    @overload
    def __getitem__(self, axis_slice: slice) -> NDArray1DFloat64: ...
    def __iter__(self) -> typing.Iterator[float]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def is_periodic(self) -> bool: ...
    @property
    def period(self) -> float | None: ...

class Binning1DFloat32(Binning2DFloat32):
    def __init__(
        self, x: Axis, range: tuple[float, float] | None = ...
    ) -> None: ...
    def push(  # type: ignore[override]
        self,
        x: NDArray1DFloat32,
        z: NDArray1DFloat32,
        weights: NDArray1DFloat32 | None = ...,
    ) -> None: ...
    def range(self) -> tuple[float, float]: ...

class Binning1DFloat64(Binning2DFloat64):
    def __init__(
        self, x: Axis, range: tuple[float, float] | None = ...
    ) -> None: ...
    def push(  # type: ignore[override]
        self,
        x: NDArray1DFloat64,
        z: NDArray1DFloat64,
        weights: NDArray1DFloat64 | None = ...,
    ) -> None: ...
    def range(self) -> tuple[float, float]: ...

class Binning2DFloat32:
    def __init__(
        self, x: Axis, y: Axis, wgs: geodetic.Spheroid | None = ...
    ) -> None: ...
    def clear(self) -> None: ...
    def count(self) -> NDArray2DUInt64: ...
    def kurtosis(self) -> NDArray2DFloat32: ...
    def max(self) -> NDArray2DFloat32: ...
    def mean(self) -> NDArray2DFloat32: ...
    def min(self) -> NDArray2DFloat32: ...
    def push(
        self,
        x: NDArray1DFloat32,
        y: NDArray1DFloat32,
        z: NDArray1DFloat32,
        simple: bool = ...,
    ) -> None: ...
    def skewness(self) -> NDArray2DFloat32: ...
    def sum(self) -> NDArray2DFloat32: ...
    def sum_of_weights(self) -> NDArray2DFloat32: ...
    def variance(self, ddof: int = ...) -> NDArray2DFloat32: ...
    def __copy__(self) -> Binning2DFloat32: ...
    def __iadd__(self, other: Binning2DFloat32) -> Binning2DFloat32: ...
    @property
    def spheroid(self) -> geodetic.Spheroid | None: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...

class Binning2DFloat64:
    def __init__(
        self, x: Axis, y: Axis, wgs: geodetic.Spheroid | None = ...
    ) -> None: ...
    def clear(self) -> None: ...
    def count(self) -> NDArray2DUInt64: ...
    def kurtosis(self) -> NDArray2DFloat64: ...
    def max(self) -> NDArray2DFloat64: ...
    def mean(self) -> NDArray2DFloat64: ...
    def min(self) -> NDArray2DFloat64: ...
    def push(
        self,
        x: NDArray1DFloat64,
        y: NDArray1DFloat64,
        z: NDArray1DFloat64,
        simple: bool = ...,
    ) -> None: ...
    def skewness(self) -> NDArray2DFloat64: ...
    def sum(self) -> NDArray2DFloat64: ...
    def sum_of_weights(self) -> NDArray2DFloat64: ...
    def variance(self, ddof: int = ...) -> NDArray2DFloat64: ...
    def __copy__(self) -> Binning2DFloat64: ...
    def __iadd__(self, other: Binning2DFloat64) -> Binning2DFloat64: ...
    @property
    def spheroid(self) -> geodetic.Spheroid | None: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...

class GridHolder:
    """The actual C++ bound class for all grids."""
    def __getstate__(self) -> tuple: ...
    def __repr__(self) -> str: ...
    @property
    def array(self) -> np.ndarray: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def has_temporal_axis(self) -> bool: ...
    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def temporal_axis_index(self) -> int: ...

class Grid1D(GridHolder):
    """1-dimensional grid."""
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> None: ...
    @property
    def z(self) -> None: ...
    @property
    def u(self) -> None: ...

class Grid2D(GridHolder):
    """2-dimensional grid."""
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> None: ...
    @property
    def u(self) -> None: ...

class Grid3D(GridHolder):
    """3-dimensional grid with spatial z-axis."""
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...
    @property
    def u(self) -> None: ...

class TemporalGrid3D(GridHolder):
    """3-dimensional grid with temporal z-axis."""
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...
    @property
    def u(self) -> None: ...

class Grid4D(GridHolder):
    """4-dimensional grid with spatial z-axis."""
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...
    @property
    def u(self) -> Axis: ...

class TemporalGrid4D(GridHolder):
    """4-dimensional grid with temporal z-axis."""
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...
    @property
    def u(self) -> Axis: ...

class RTree3DFloat32:
    def __init__(self, spheroid: geodetic.Spheroid | None = ...) -> None: ...
    def bounds(self) -> tuple[Vector3Float32, Vector3Float32] | None: ...
    def clear(self) -> None: ...
    def empty(self) -> bool: ...
    def insert(
        self, coordinates: NDArray2DFloat32, values: NDArray1DFloat32
    ) -> None: ...
    def inverse_distance_weighting(
        self,
        coordinates: NDArray2DFloat32,
        config: rtree.InverseDistanceWeighting | None = ...,
    ) -> tuple[NDArray1DFloat32, NDArray1DUInt32]: ...
    def kriging(
        self, coordinates: NDArray2DFloat32, config: rtree.Kriging | None = ...
    ) -> tuple[NDArray1DFloat32, NDArray1DUInt32]: ...
    def packing(self, coordinates: NDArray2DFloat32, values) -> None: ...
    def query(
        self, coordinates: NDArray2DFloat32, config: rtree.Query | None = ...
    ) -> tuple[NDArray2DFloat32, NDArray2DFloat32]: ...
    def radial_basis_function(
        self,
        coordinates: NDArray2DFloat32,
        config: rtree.RadialBasisFunction | None = ...,
    ) -> tuple[NDArray1DFloat32, NDArray1DUInt32]: ...
    def size(self) -> int: ...
    def window_function(
        self,
        coordinates: NDArray2DFloat32,
        config: rtree.InterpolationWindow | None = ...,
    ) -> tuple[NDArray1DFloat32, NDArray1DUInt32]: ...
    @property
    def spheroid(self) -> geodetic.Spheroid | None: ...

class RTree3DFloat64:
    def __init__(self, spheroid: geodetic.Spheroid | None = ...) -> None: ...
    def bounds(self) -> tuple[Vector3Float64, Vector3Float64] | None: ...
    def clear(self) -> None: ...
    def empty(self) -> bool: ...
    def insert(
        self, coordinates: NDArray2DFloat64, values: NDArray1DFloat64
    ) -> None: ...
    def inverse_distance_weighting(
        self,
        coordinates: NDArray2DFloat64,
        config: rtree.InverseDistanceWeighting | None = ...,
    ) -> tuple[NDArray1DFloat64, NDArray1DUInt32]: ...
    def kriging(
        self, coordinates: NDArray2DFloat64, config: rtree.Kriging | None = ...
    ) -> tuple[NDArray1DFloat64, NDArray1DUInt32]: ...
    def packing(
        self, coordinates: NDArray2DFloat64, values: NDArray1DFloat64
    ) -> None: ...
    def query(
        self, coordinates: NDArray2DFloat64, config: rtree.Query | None = ...
    ) -> tuple[NDArray2DFloat64, NDArray2DFloat64]: ...
    def radial_basis_function(
        self,
        coordinates: NDArray2DFloat64,
        config: rtree.RadialBasisFunction | None = ...,
    ) -> tuple[NDArray1DFloat64, NDArray1DUInt32]: ...
    def size(self) -> int: ...
    def window_function(
        self, coordinates, config: rtree.InterpolationWindow | None = ...
    ) -> tuple[NDArray1DFloat64, NDArray1DUInt32]: ...
    @property
    def spheroid(self) -> geodetic.Spheroid | None: ...

_TemporalScalar = TypeVar("_TemporalScalar", np.datetime64, np.timedelta64)
_TemporalArray = TypeVar(
    "_TemporalArray", NDArray1DDateTime64, NDArray1DTimeDelta64
)

class TemporalAxis(Generic[_TemporalScalar, _TemporalArray]):
    """A temporal coordinate axis for grid interpolation."""

    @overload
    def __init__(
        self: TemporalAxis[np.datetime64, NDArray1DDateTime64],
        points: NDArray1DDateTime64,
        epsilon: np.timedelta64 | None = ...,
        period: np.timedelta64 | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self: TemporalAxis[np.timedelta64, NDArray1DTimeDelta64],
        points: NDArray1DTimeDelta64,
        epsilon: np.timedelta64 | None = ...,
        period: np.timedelta64 | None = ...,
    ) -> None: ...
    def back(self) -> _TemporalScalar: ...
    def cast_to_temporal_axis(
        self, array: _TemporalArray
    ) -> _TemporalArray: ...
    def find_index(
        self, array: _TemporalArray, bounded: bool = ...
    ) -> NDArray1DInt64: ...
    def find_indexes(self, array: _TemporalArray) -> NDArray2DInt64: ...
    def flip(
        self, inplace: bool = ...
    ) -> TemporalAxis[_TemporalScalar, _TemporalArray]: ...
    def front(self) -> _TemporalScalar: ...
    def increment(self, step: int = ...) -> np.timedelta64: ...
    def is_ascending(self) -> bool: ...
    def is_regular(self) -> bool: ...
    def max_value(self) -> _TemporalScalar: ...
    def min_value(self) -> _TemporalScalar: ...
    def __copy__(self) -> TemporalAxis[_TemporalScalar, _TemporalArray]: ...
    def __eq__(self, other: object) -> bool: ...
    @overload
    def __getitem__(self, index: int) -> _TemporalScalar: ...
    @overload
    def __getitem__(self, axis_slice: slice) -> _TemporalArray: ...
    def __iter__(self) -> typing.Iterator[_TemporalScalar]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def is_periodic(self) -> bool: ...
    @property
    def period(self) -> np.timedelta64 | None: ...

@overload
def Grid(
    x: Axis,
    array: object,
) -> Grid1D: ...
@overload
def Grid(
    x: Axis,
    y: Axis,
    array: object,
) -> Grid2D: ...
@overload
def Grid(
    x: Axis,
    y: Axis,
    z: Axis,
    array: object,
) -> Grid3D: ...
@overload
def Grid(
    x: Axis,
    y: Axis,
    z: TemporalAxis,
    array: object,
) -> TemporalGrid3D: ...
@overload
def Grid(
    x: Axis,
    y: Axis,
    z: Axis,
    u: Axis,
    array: object,
) -> Grid4D: ...
@overload
def Grid(
    x: Axis,
    y: Axis,
    z: TemporalAxis,
    u: Axis,
    array: object,
) -> TemporalGrid4D: ...
