import typing
from typing import Any, overload

from ..type_hints import (NDArray1DDateTime64, NDArray1DFloat32,
                          NDArray1DFloat64, NDArray1DTimeDelta64)
from .config import geometric

@overload
def bivariate(
    grid: Grid2DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    config: geometric.Bivariate,
) -> NDArray1DFloat64: ...
@overload
def bivariate(
    grid: Grid2DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    config: geometric.Bivariate,
) -> NDArray1DFloat64: ...
@overload
def bivariate(
    grid: Grid2DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    config: geometric.Bivariate,
) -> NDArray1DFloat64: ...
@overload
def trivariate(
    grid: Grid3DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    config: geometric.Trivariate,
) -> NDArray1DFloat64: ...
@overload
def trivariate(
    grid: Grid3DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    config: geometric.Trivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: Grid3DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    config: geometric.Trivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: TemporalGrid3DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    config: geometric.Trivariate,
) -> NDArray1DFloat64: ...
@overload
def trivariate(
    grid: TemporalGrid3DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    config: geometric.Trivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: TemporalGrid3DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    config: geometric.Trivariate,
) -> NDArray1DFloat32: ...

class Axis:
    def __init__(
        self,
        values,
        epsilon: float = ...,
        period: float | None = ...,
    ) -> None: ...
    def back(self) -> float: ...
    def find_index(self, *args, **kwargs): ...
    def find_indexes(self, *args, **kwargs): ...
    def flip(self, inplace: bool = ...) -> Axis: ...
    def front(self) -> float: ...
    @overload
    def increment(self) -> float: ...
    @overload
    def increment(self, step) -> Any: ...
    def is_ascending(self) -> bool: ...
    def is_regular(self) -> bool: ...
    def max_value(self) -> float: ...
    def min_value(self) -> float: ...
    def __copy__(self) -> Axis: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, index: int) -> float: ...
    def __iter__(self) -> typing.Iterator[float]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def is_periodic(self) -> bool: ...
    @property
    def period(self) -> float | None: ...

class Grid1DFloat32:
    def __init__(self, x: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...

class Grid1DFloat64:
    def __init__(self, x: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...

class Grid1DInt8:
    def __init__(self, x: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...

class Grid2DFloat32:
    def __init__(self, x: Axis, y: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...

class Grid2DFloat64:
    def __init__(self, x: Axis, y: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...

class Grid2DInt8:
    def __init__(self, x: Axis, y: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...

class Grid3DFloat32:
    def __init__(self, x: Axis, y: Axis, z: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class Grid3DFloat64:
    def __init__(self, x: Axis, y: Axis, z: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class Grid3DInt8:
    def __init__(self, x: Axis, y: Axis, z: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class Grid4DFloat32:
    def __init__(self, x: Axis, y: Axis, z: Axis, u: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class Grid4DFloat64:
    def __init__(self, x: Axis, y: Axis, z: Axis, u: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class Grid4DInt8:
    def __init__(self, x: Axis, y: Axis, z: Axis, u: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class TemporalAxis(TemporalAxisBase):
    def __init__(
        self,
        points: object,
        epsilon: object | None = ...,
        period: object | None = ...,
    ) -> None: ...
    def back(self) -> object: ...
    def cast_to_temporal_axis(self, array: object) -> object: ...
    def find_index(self, *args, **kwargs): ...
    def find_indexes(self, *args, **kwargs): ...
    def flip(self, inplace: bool = ...) -> TemporalAxis: ...
    def front(self) -> object: ...
    @overload
    def increment(self) -> object: ...
    @overload
    def increment(self, step) -> Any: ...
    def is_ascending(self) -> bool: ...
    def is_regular(self) -> bool: ...
    def max_value(self) -> object: ...
    def min_value(self) -> object: ...
    def __copy__(self) -> TemporalAxis: ...
    def __eq__(self, other: object) -> bool: ...
    @overload
    def __getitem__(self, index: int) -> object: ...
    @overload
    def __getitem__(self, arg: slice) -> object: ...
    def __iter__(self) -> typing.Iterator[object]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def dtype(self) -> object: ...
    @property
    def is_periodic(self) -> bool: ...
    @property
    def period(self) -> object: ...

class TemporalAxisBase:
    def __init__(self, *args, **kwargs) -> None: ...

class TemporalGrid3DFloat32:
    def __init__(self, x: Axis, y: Axis, z: TemporalAxis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...

class TemporalGrid3DFloat64:
    def __init__(self, x: Axis, y: Axis, z: TemporalAxis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...

class TemporalGrid3DInt8:
    def __init__(self, x: Axis, y: Axis, z: TemporalAxis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...

class TemporalGrid4DFloat32:
    def __init__(
        self,
        x: Axis,
        y: Axis,
        z: TemporalAxis,
        u: Axis,
        array,
    ) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...

class TemporalGrid4DFloat64:
    def __init__(
        self,
        x: Axis,
        y: Axis,
        z: TemporalAxis,
        u: Axis,
        array,
    ) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...

class TemporalGrid4DInt8:
    def __init__(
        self,
        x: Axis,
        y: Axis,
        z: TemporalAxis,
        u: Axis,
        array,
    ) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...
