import typing
from typing import Any, Generic, TypeVar, overload

import numpy as np

from ..type_hints import (
    NDArray1DDateTime64,
    NDArray1DFloat32,
    NDArray1DFloat64,
    NDArray1DInt64,
    NDArray1DTimeDelta64,
    NDArray1DUInt32,
    NDArray2DFloat32,
    NDArray2DFloat64,
    NDArray2DInt64,
    NDArray2DUInt64,
    Vector3Float32,
    Vector3Float64,
)
from . import geodetic
from .config import geometric, rtree, windowed

@overload
def bivariate(
    grid: Grid2DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    config: geometric.Bivariate,
) -> NDArray1DFloat64: ...
@overload
def bivariate(
    grid: Grid2DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    config: geometric.Bivariate,
) -> NDArray1DFloat64: ...
@overload
def bivariate(
    grid: Grid2DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    config: geometric.Bivariate,
) -> NDArray1DFloat64: ...
@overload
def bivariate(
    grid: Grid2DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    config: windowed.Bivariate,
) -> NDArray1DFloat64: ...
@overload
def bivariate(
    grid: Grid2DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    config: windowed.Bivariate,
) -> NDArray1DFloat32: ...
@overload
def bivariate(
    grid: Grid2DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    config: windowed.Bivariate,
) -> NDArray1DFloat32: ...
@overload
def quadrivariate(
    grid: Grid4DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    u: NDArray1DFloat64,
    config: geometric.Quadrivariate,
) -> NDArray1DFloat64: ...
@overload
def quadrivariate(
    grid: Grid4DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    u: NDArray1DFloat64,
    config: geometric.Quadrivariate,
) -> NDArray1DFloat32: ...
@overload
def quadrivariate(
    grid: Grid4DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    u: NDArray1DFloat64,
    config: geometric.Quadrivariate,
) -> NDArray1DFloat32: ...
@overload
def quadrivariate(
    grid: TemporalGrid4DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    u: NDArray1DFloat64,
    config: geometric.Quadrivariate,
) -> NDArray1DFloat64: ...
@overload
def quadrivariate(
    grid: TemporalGrid4DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    u: NDArray1DFloat64,
    config: geometric.Quadrivariate,
) -> NDArray1DFloat32: ...
@overload
def quadrivariate(
    grid: TemporalGrid4DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    u: NDArray1DFloat64,
    config: geometric.Quadrivariate,
) -> NDArray1DFloat32: ...
@overload
def quadrivariate(
    grid: Grid4DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    u: NDArray1DFloat64,
    config: windowed.Quadrivariate,
) -> NDArray1DFloat64: ...
@overload
def quadrivariate(
    grid: Grid4DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    u: NDArray1DFloat64,
    config: windowed.Quadrivariate,
) -> NDArray1DFloat32: ...
@overload
def quadrivariate(
    grid: Grid4DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    u: NDArray1DFloat64,
    config: windowed.Quadrivariate,
) -> NDArray1DFloat32: ...
@overload
def quadrivariate(
    grid: TemporalGrid4DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    u: NDArray1DFloat64,
    config: windowed.Quadrivariate,
) -> NDArray1DFloat64: ...
@overload
def quadrivariate(
    grid: TemporalGrid4DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    u: NDArray1DFloat64,
    config: windowed.Quadrivariate,
) -> NDArray1DFloat32: ...
@overload
def quadrivariate(
    grid: TemporalGrid4DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    u: NDArray1DFloat64,
    config: windowed.Quadrivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: Grid3DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    config: geometric.Trivariate,
) -> NDArray1DFloat64: ...
@overload
def trivariate(
    grid: Grid3DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    config: geometric.Trivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: Grid3DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    config: geometric.Trivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: TemporalGrid3DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    config: geometric.Trivariate,
) -> NDArray1DFloat64: ...
@overload
def trivariate(
    grid: TemporalGrid3DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    config: geometric.Trivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: TemporalGrid3DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    config: geometric.Trivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: Grid3DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    config: windowed.Trivariate,
) -> NDArray1DFloat64: ...
@overload
def trivariate(
    grid: Grid3DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    config: windowed.Trivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: Grid3DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DFloat64,
    config: windowed.Trivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: TemporalGrid3DFloat64,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    config: windowed.Trivariate,
) -> NDArray1DFloat64: ...
@overload
def trivariate(
    grid: TemporalGrid3DFloat32,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    config: windowed.Trivariate,
) -> NDArray1DFloat32: ...
@overload
def trivariate(
    grid: TemporalGrid3DInt8,
    x: NDArray1DFloat64,
    y: NDArray1DFloat64,
    z: NDArray1DDateTime64 | NDArray1DTimeDelta64,
    config: windowed.Trivariate,
) -> NDArray1DFloat32: ...

class Axis:
    def __init__(
        self,
        values,
        epsilon: float = ...,
        period: float | None = ...,
    ) -> None: ...
    def back(self) -> float: ...
    def find_index(self, *args, **kwargs): ...
    def find_indexes(self, *args, **kwargs): ...
    def flip(self, inplace: bool = ...) -> Axis: ...
    def front(self) -> float: ...
    @overload
    def increment(self) -> float: ...
    @overload
    def increment(self, step) -> Any: ...
    def is_ascending(self) -> bool: ...
    def is_regular(self) -> bool: ...
    def max_value(self) -> float: ...
    def min_value(self) -> float: ...
    def __copy__(self) -> Axis: ...
    def __eq__(self, other: object) -> bool: ...
    @overload
    def __getitem__(self, index: int) -> float: ...
    @overload
    def __getitem__(self, axis_slice: slice) -> NDArray1DFloat64: ...
    def __iter__(self) -> typing.Iterator[float]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def is_periodic(self) -> bool: ...
    @property
    def period(self) -> float | None: ...

class Binning1DFloat32(Binning2DFloat32):
    def __init__(
        self, x: Axis, range: tuple[float, float] | None = ...
    ) -> None: ...
    def push(  # type: ignore[override]
        self,
        x: NDArray1DFloat32,
        z: NDArray1DFloat32,
        weights: NDArray1DFloat32 | None = ...,
    ) -> None: ...
    def range(self) -> tuple[float, float]: ...

class Binning1DFloat64(Binning2DFloat64):
    def __init__(
        self, x: Axis, range: tuple[float, float] | None = ...
    ) -> None: ...
    def push(  # type: ignore[override]
        self,
        x: NDArray1DFloat64,
        z: NDArray1DFloat64,
        weights: NDArray1DFloat64 | None = ...,
    ) -> None: ...
    def range(self) -> tuple[float, float]: ...

class Binning2DFloat32:
    def __init__(
        self, x: Axis, y: Axis, wgs: geodetic.Spheroid | None = ...
    ) -> None: ...
    def clear(self) -> None: ...
    def count(self) -> NDArray2DUInt64: ...
    def kurtosis(self) -> NDArray2DFloat32: ...
    def max(self) -> NDArray2DFloat32: ...
    def mean(self) -> NDArray2DFloat32: ...
    def min(self) -> NDArray2DFloat32: ...
    def push(
        self,
        x: NDArray1DFloat32,
        y: NDArray1DFloat32,
        z: NDArray1DFloat32,
        simple: bool = ...,
    ) -> None: ...
    def skewness(self) -> NDArray2DFloat32: ...
    def sum(self) -> NDArray2DFloat32: ...
    def sum_of_weights(self) -> NDArray2DFloat32: ...
    def variance(self, ddof: int = ...) -> NDArray2DFloat32: ...
    def __copy__(self) -> Binning2DFloat32: ...
    def __iadd__(self, other: Binning2DFloat32) -> Binning2DFloat32: ...
    @property
    def spheroid(self) -> geodetic.Spheroid | None: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...

class Binning2DFloat64:
    def __init__(
        self, x: Axis, y: Axis, wgs: geodetic.Spheroid | None = ...
    ) -> None: ...
    def clear(self) -> None: ...
    def count(self) -> NDArray2DUInt64: ...
    def kurtosis(self) -> NDArray2DFloat64: ...
    def max(self) -> NDArray2DFloat64: ...
    def mean(self) -> NDArray2DFloat64: ...
    def min(self) -> NDArray2DFloat64: ...
    def push(
        self,
        x: NDArray1DFloat64,
        y: NDArray1DFloat64,
        z: NDArray1DFloat64,
        simple: bool = ...,
    ) -> None: ...
    def skewness(self) -> NDArray2DFloat64: ...
    def sum(self) -> NDArray2DFloat64: ...
    def sum_of_weights(self) -> NDArray2DFloat64: ...
    def variance(self, ddof: int = ...) -> NDArray2DFloat64: ...
    def __copy__(self) -> Binning2DFloat64: ...
    def __iadd__(self, other: Binning2DFloat64) -> Binning2DFloat64: ...
    @property
    def spheroid(self) -> geodetic.Spheroid | None: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...

class Grid1DFloat32:
    def __init__(self, x: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...

class Grid1DFloat64:
    def __init__(self, x: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...

class Grid1DInt8:
    def __init__(self, x: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...

class Grid2DFloat32:
    def __init__(self, x: Axis, y: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...

class Grid2DFloat64:
    def __init__(self, x: Axis, y: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...

class Grid2DInt8:
    def __init__(self, x: Axis, y: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...

class Grid3DFloat32:
    def __init__(self, x: Axis, y: Axis, z: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class Grid3DFloat64:
    def __init__(self, x: Axis, y: Axis, z: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class Grid3DInt8:
    def __init__(self, x: Axis, y: Axis, z: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class Grid4DFloat32:
    def __init__(self, x: Axis, y: Axis, z: Axis, u: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class Grid4DFloat64:
    def __init__(self, x: Axis, y: Axis, z: Axis, u: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class Grid4DInt8:
    def __init__(self, x: Axis, y: Axis, z: Axis, u: Axis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> Axis: ...

class RTree3DFloat32:
    def __init__(self, spheroid: geodetic.Spheroid | None = ...) -> None: ...
    def bounds(self) -> tuple[Vector3Float32, Vector3Float32] | None: ...
    def clear(self) -> None: ...
    def empty(self) -> bool: ...
    def insert(
        self, coordinates: NDArray2DFloat32, values: NDArray1DFloat32
    ) -> None: ...
    def inverse_distance_weighting(
        self,
        coordinates: NDArray2DFloat32,
        config: rtree.InverseDistanceWeighting | None = ...,
    ) -> tuple[NDArray1DFloat32, NDArray1DUInt32]: ...
    def kriging(
        self, coordinates: NDArray2DFloat32, config: rtree.Kriging | None = ...
    ) -> tuple[NDArray1DFloat32, NDArray1DUInt32]: ...
    def packing(self, coordinates: NDArray2DFloat32, values) -> None: ...
    def query(
        self, coordinates: NDArray2DFloat32, config: rtree.Query | None = ...
    ) -> tuple[NDArray2DFloat32, NDArray2DFloat32]: ...
    def radial_basis_function(
        self,
        coordinates: NDArray2DFloat32,
        config: rtree.RadialBasisFunction | None = ...,
    ) -> tuple[NDArray1DFloat32, NDArray1DUInt32]: ...
    def size(self) -> int: ...
    def window_function(
        self,
        coordinates: NDArray2DFloat32,
        config: rtree.InterpolationWindow | None = ...,
    ) -> tuple[NDArray1DFloat32, NDArray1DUInt32]: ...
    @property
    def spheroid(self) -> geodetic.Spheroid | None: ...

class RTree3DFloat64:
    def __init__(self, spheroid: geodetic.Spheroid | None = ...) -> None: ...
    def bounds(self) -> tuple[Vector3Float64, Vector3Float64] | None: ...
    def clear(self) -> None: ...
    def empty(self) -> bool: ...
    def insert(
        self, coordinates: NDArray2DFloat64, values: NDArray1DFloat64
    ) -> None: ...
    def inverse_distance_weighting(
        self,
        coordinates: NDArray2DFloat64,
        config: rtree.InverseDistanceWeighting | None = ...,
    ) -> tuple[NDArray1DFloat64, NDArray1DUInt32]: ...
    def kriging(
        self, coordinates: NDArray2DFloat64, config: rtree.Kriging | None = ...
    ) -> tuple[NDArray1DFloat64, NDArray1DUInt32]: ...
    def packing(
        self, coordinates: NDArray2DFloat64, values: NDArray1DFloat64
    ) -> None: ...
    def query(
        self, coordinates: NDArray2DFloat64, config: rtree.Query | None = ...
    ) -> tuple[NDArray2DFloat64, NDArray2DFloat64]: ...
    def radial_basis_function(
        self,
        coordinates: NDArray2DFloat64,
        config: rtree.RadialBasisFunction | None = ...,
    ) -> tuple[NDArray1DFloat64, NDArray1DUInt32]: ...
    def size(self) -> int: ...
    def window_function(
        self, coordinates, config: rtree.InterpolationWindow | None = ...
    ) -> tuple[NDArray1DFloat64, NDArray1DUInt32]: ...
    @property
    def spheroid(self) -> geodetic.Spheroid | None: ...

_TemporalScalar = TypeVar("_TemporalScalar", np.datetime64, np.timedelta64)
_TemporalArray = TypeVar(
    "_TemporalArray", NDArray1DDateTime64, NDArray1DTimeDelta64
)

class TemporalAxis(Generic[_TemporalScalar, _TemporalArray]):
    @overload
    def __init__(
        self: TemporalAxis[np.datetime64, NDArray1DDateTime64],
        points: NDArray1DDateTime64,
        epsilon: np.timedelta64 | None = ...,
        period: np.timedelta64 | None = ...,
    ) -> None: ...
    @overload
    def __init__(
        self: TemporalAxis[np.timedelta64, NDArray1DTimeDelta64],
        points: NDArray1DTimeDelta64,
        epsilon: np.timedelta64 | None = ...,
        period: np.timedelta64 | None = ...,
    ) -> None: ...
    def back(self) -> _TemporalScalar: ...
    def cast_to_temporal_axis(
        self, array: _TemporalArray
    ) -> _TemporalArray: ...
    def find_index(
        self, array: _TemporalArray, bounded: bool = ...
    ) -> NDArray1DInt64: ...
    def find_indexes(self, array: _TemporalArray) -> NDArray2DInt64: ...
    def flip(
        self, inplace: bool = ...
    ) -> TemporalAxis[_TemporalScalar, _TemporalArray]: ...
    def front(self) -> _TemporalScalar: ...
    def increment(self, step: int = ...) -> np.timedelta64: ...
    def is_ascending(self) -> bool: ...
    def is_regular(self) -> bool: ...
    def max_value(self) -> _TemporalScalar: ...
    def min_value(self) -> _TemporalScalar: ...
    def __copy__(self) -> TemporalAxis[_TemporalScalar, _TemporalArray]: ...
    def __eq__(self, other: object) -> bool: ...
    @overload
    def __getitem__(self, index: int) -> _TemporalScalar: ...
    @overload
    def __getitem__(self, axis_slice: slice) -> _TemporalArray: ...
    def __iter__(self) -> typing.Iterator[_TemporalScalar]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def is_periodic(self) -> bool: ...
    @property
    def period(self) -> np.timedelta64 | None: ...

class TemporalGrid3DFloat32:
    def __init__(self, x: Axis, y: Axis, z: TemporalAxis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...

class TemporalGrid3DFloat64:
    def __init__(self, x: Axis, y: Axis, z: TemporalAxis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...

class TemporalGrid3DInt8:
    def __init__(self, x: Axis, y: Axis, z: TemporalAxis, array) -> None: ...
    @property
    def array(self): ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...

class TemporalGrid4DFloat32:
    def __init__(
        self,
        x: Axis,
        y: Axis,
        z: TemporalAxis,
        u: Axis,
        array,
    ) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...

class TemporalGrid4DFloat64:
    def __init__(
        self,
        x: Axis,
        y: Axis,
        z: TemporalAxis,
        u: Axis,
        array,
    ) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...

class TemporalGrid4DInt8:
    def __init__(
        self,
        x: Axis,
        y: Axis,
        z: TemporalAxis,
        u: Axis,
        array,
    ) -> None: ...
    @property
    def array(self): ...
    @property
    def u(self) -> Axis: ...
    @property
    def x(self) -> Axis: ...
    @property
    def y(self) -> Axis: ...
    @property
    def z(self) -> TemporalAxis: ...
