from typing import overload

from ..type_hints import NDArray1DFloat64

class Coordinates:
    def __init__(self, spheroid: Spheroid | None = ...) -> None: ...
    def ecef_to_lla(
        self,
        x: NDArray1DFloat64,
        y: NDArray1DFloat64,
        z: NDArray1DFloat64,
        num_threads: int = 0,
    ) -> tuple[NDArray1DFloat64, NDArray1DFloat64, NDArray1DFloat64]: ...
    def lla_to_ecef(
        self,
        lon: NDArray1DFloat64,
        lat: NDArray1DFloat64,
        alt: NDArray1DFloat64,
        num_threads: int = 0,
    ) -> tuple[NDArray1DFloat64, NDArray1DFloat64, NDArray1DFloat64]: ...
    def transform(
        self,
        target: Coordinates,
        lon: NDArray1DFloat64,
        lat: NDArray1DFloat64,
        alt: NDArray1DFloat64,
        num_threads: int = 0,
    ) -> tuple[NDArray1DFloat64, NDArray1DFloat64, NDArray1DFloat64]: ...
    @property
    def spheroid(self) -> Spheroid: ...

class Spheroid:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, semi_major_axis: float, flattening: float) -> None: ...
    def authalic_radius(self) -> float: ...
    def axis_ratio(self) -> float: ...
    def equatorial_circumference(
        self, semi_major_axis: bool = ...
    ) -> float: ...
    def equatorial_radius_of_curvature(self) -> float: ...
    def first_eccentricity_squared(self) -> float: ...
    def geocentric_radius(self, lat: float) -> float: ...
    def linear_eccentricity(self) -> float: ...
    def mean_radius(self) -> float: ...
    def polar_radius_of_curvature(self) -> float: ...
    def second_eccentricity_squared(self) -> float: ...
    def semi_minor_axis(self) -> float: ...
    def volumetric_radius(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def flattening(self) -> float: ...
    @property
    def semi_major_axis(self) -> float: ...
