from typing import Iterator, overload
import numpy as np


class Period:
    def __init__(self, begin: np.datetime64, end: np.datetime64, within: bool = ...) -> None: ...
    def contains(self, point_or_period: np.datetime64 | Period) -> bool: ...
    def duration(self) -> np.timedelta64: ...
    def end(self) -> np.datetime64: ...
    def extend(self, point: np.datetime64) -> Period: ...
    def intersection(self, other: Period) -> Period | None: ...
    def intersects(self, other: Period) -> bool: ...
    def is_adjacent(self, other: Period) -> bool: ...
    def is_after(self, point: np.datetime64) -> bool: ...
    def is_before(self, point: np.datetime64) -> bool: ...
    def is_close(self, date: object, tolerance: object) -> bool: ...
    def merge(self, other: Period) -> Period | None: ...
    def shift(self, offset: np.timedelta64) -> Period: ...
    def __eq__(self, arg: object) -> bool: ...
    def __ge__(self, arg: object) -> bool: ...
    def __gt__(self, arg: object) -> bool: ...
    def __le__(self, arg: object) -> bool: ...
    def __lt__(self, arg: object) -> bool: ...
    def __ne__(self, arg: object) -> bool: ...
    @property
    def begin(self) -> np.datetime64: ...
    @property
    def last(self) -> np.datetime64: ...
    @property
    def resolution(self) -> np.dtype: ...

class PeriodList:
    def __init__(self, periods: list | None = ...) -> None: ...
    def append(self, period: Period) -> None: ...
    def extend(self, periods: PeriodList) -> None: ...
    def find_containing(self, date: object) -> Period | None: ...
    def insert(self, index: int, period: Period) -> None: ...
    def is_close(self, date: object, tolerance: object) -> bool: ...
    def is_sorted_and_disjoint(self) -> bool: ...
    def pop(self, index: int = ...) -> Period: ...
    def total_duration(self) -> object: ...
    @overload
    def __delitem__(self, index: int) -> None: ...
    @overload
    def __delitem__(self, index_slice: slice) -> None: ...
    @overload
    def __getitem__(self, arg: int) -> Period: ...
    @overload
    def __getitem__(self, index_slice: slice) -> PeriodList: ...
    def __iter__(self) -> Iterator[Period]: ...
    def __len__(self) -> int: ...
    @overload
    def __setitem__(self, index: int, value: Period) -> None: ...
    @overload
    def __setitem__(self, index_slice: slice, values: PeriodList) -> None: ...
    @property
    def resolution(self) -> np.dtype: ...
