from typing import Callable, ClassVar

class Bivariate:
    bilinear: ClassVar[Callable[[], Bivariate]] = ...
    idw: ClassVar[Callable[[], Bivariate]] = ...
    nearest: ClassVar[Callable[[], Bivariate]] = ...
    def __init__(self) -> None: ...
    def bounds_error(self, value: bool) -> Bivariate: ...
    def num_threads(self, value: int) -> Bivariate: ...

class Quadrivariate:
    bilinear: ClassVar[Callable[[], Quadrivariate]] = ...
    idw: ClassVar[Callable[[], Quadrivariate]] = ...
    nearest: ClassVar[Callable[[], Quadrivariate]] = ...
    def __init__(self) -> None: ...
    def bounds_error(self, value: bool) -> Quadrivariate: ...
    def num_threads(self, value: int) -> Quadrivariate: ...

class Trivariate:
    bilinear: ClassVar[Callable[[], Trivariate]] = ...
    idw: ClassVar[Callable[[], Trivariate]] = ...
    nearest: ClassVar[Callable[[], Trivariate]] = ...
    def __init__(self) -> None: ...
    def bounds_error(self, value: bool) -> Trivariate: ...
    def num_threads(self, value: int) -> Trivariate: ...
