import enum
from typing import Callable, ClassVar

class Bivariate:
    akima: ClassVar[Callable[[], Bivariate]] = ...
    akima_periodic: ClassVar[Callable[[], Bivariate]] = ...
    bicubic: ClassVar[Callable[[], Bivariate]] = ...
    bilinear: ClassVar[Callable[[], Bivariate]] = ...
    c_spline: ClassVar[Callable[[], Bivariate]] = ...
    c_spline_not_a_knot: ClassVar[Callable[[], Bivariate]] = ...
    c_spline_periodic: ClassVar[Callable[[], Bivariate]] = ...
    linear: ClassVar[Callable[[], Bivariate]] = ...
    polynomial: ClassVar[Callable[[], Bivariate]] = ...
    steffen: ClassVar[Callable[[], Bivariate]] = ...
    def __init__(self) -> None: ...
    def bounds_error(self, value: bool) -> Bivariate: ...
    def num_threads(self, value: int) -> Bivariate: ...
    def with_boundary_mode(self, mode: Boundary) -> Bivariate: ...
    def with_bounds_error(self, value: bool) -> Bivariate: ...
    def with_num_threads(self, value: int) -> Bivariate: ...
    def with_window_size_x(self, size: int) -> Bivariate: ...
    def with_window_size_y(self, size: int) -> Bivariate: ...

class Boundary(enum.Enum):
    EXPAND = ...
    SYM = ...
    UNDEF = ...
    WRAP = ...

class Quadrivariate:
    akima: ClassVar[Callable[[], Quadrivariate]] = ...
    akima_periodic: ClassVar[Callable[[], Quadrivariate]] = ...
    bicubic: ClassVar[Callable[[], Quadrivariate]] = ...
    bilinear: ClassVar[Callable[[], Quadrivariate]] = ...
    c_spline: ClassVar[Callable[[], Quadrivariate]] = ...
    c_spline_not_a_knot: ClassVar[Callable[[], Quadrivariate]] = ...
    c_spline_periodic: ClassVar[Callable[[], Quadrivariate]] = ...
    linear: ClassVar[Callable[[], Quadrivariate]] = ...
    polynomial: ClassVar[Callable[[], Quadrivariate]] = ...
    steffen: ClassVar[Callable[[], Quadrivariate]] = ...
    def __init__(self) -> None: ...
    def bounds_error(self, value: bool) -> Quadrivariate: ...
    def num_threads(self, value: int) -> Quadrivariate: ...
    def with_boundary_mode(self, mode: Boundary) -> Quadrivariate: ...
    def with_bounds_error(self, value: bool) -> Quadrivariate: ...
    def with_fourth_axis(self, config) -> Quadrivariate: ...
    def with_num_threads(self, value: int) -> Quadrivariate: ...
    def with_third_axis(self, config) -> Quadrivariate: ...
    def with_window_size_x(self, size: int) -> Quadrivariate: ...
    def with_window_size_y(self, size: int) -> Quadrivariate: ...

class Trivariate:
    akima: ClassVar[Callable[[], Trivariate]] = ...
    akima_periodic: ClassVar[Callable[[], Trivariate]] = ...
    bicubic: ClassVar[Callable[[], Trivariate]] = ...
    bilinear: ClassVar[Callable[[], Trivariate]] = ...
    c_spline: ClassVar[Callable[[], Trivariate]] = ...
    c_spline_not_a_knot: ClassVar[Callable[[], Trivariate]] = ...
    c_spline_periodic: ClassVar[Callable[[], Trivariate]] = ...
    linear: ClassVar[Callable[[], Trivariate]] = ...
    polynomial: ClassVar[Callable[[], Trivariate]] = ...
    steffen: ClassVar[Callable[[], Trivariate]] = ...
    def __init__(self) -> None: ...
    def bounds_error(self, value: bool) -> Trivariate: ...
    def num_threads(self, value: int) -> Trivariate: ...
    def with_boundary_mode(self, mode: Boundary) -> Trivariate: ...
    def with_bounds_error(self, value: bool) -> Trivariate: ...
    def with_num_threads(self, value: int) -> Trivariate: ...
    def with_third_axis(self, config) -> Trivariate: ...
    def with_window_size_x(self, size: int) -> Trivariate: ...
    def with_window_size_y(self, size: int) -> Trivariate: ...
