import collections.abc
from typing import Generic, Iterator, TypeVar, overload
from ...type_hints import NDArray1DFloat64

_ConceptElement = TypeVar("_ConceptElement", Point, LineString, Polygon)

_Concept = TypeVar("_Concept", Point, LineString, Polygon, Segment, Ring,
                    Box, Spheroid, Coordinates,
                    MultiPoint, MultiLineString, MultiPolygon)

class Box:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, min_corner: tuple[float, float], max_corner: tuple[float, float]
    ) -> None: ...
    @overload
    def centroid(self) -> Point: ...
    @overload
    def centroid(self, centerpoint: Point) -> Point: ...
    def max_corner(self) -> Point: ...
    def min_corner(self) -> Point: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...

class Coordinates:
    def __init__(self, spheroid: Spheroid | None = ...) -> None: ...
    def ecef_to_lla(
        self,
        x: NDArray1DFloat64,
        y: NDArray1DFloat64,
        z: NDArray1DFloat64,
        num_threads: int = 0,
    ) -> tuple[NDArray1DFloat64, NDArray1DFloat64, NDArray1DFloat64]: ...
    def lla_to_ecef(
        self,
        lon: NDArray1DFloat64,
        lat: NDArray1DFloat64,
        alt: NDArray1DFloat64,
        num_threads: int = 0,
    ) -> tuple[NDArray1DFloat64, NDArray1DFloat64, NDArray1DFloat64]: ...
    def transform(
        self,
        target: Coordinates,
        lon: NDArray1DFloat64,
        lat: NDArray1DFloat64,
        alt: NDArray1DFloat64,
        num_threads: int = 0,
    ) -> tuple[NDArray1DFloat64, NDArray1DFloat64, NDArray1DFloat64]: ...
    @property
    def spheroid(self) -> Spheroid: ...

class LineString:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, lon: NDArray1DFloat64, lat: NDArray1DFloat64
    ) -> None: ...
    def append(self, point: Point) -> None: ...
    def clear(self) -> None: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, idx: int) -> Point: ...
    def __iter__(self) -> Iterator[Point]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setitem__(self, idx: int, point: Point) -> None: ...

class MultiLineString:
    lines: list[LineString]  # _BaseModelView[LineString]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, lines: collections.abc.Sequence[LineString] = ...
    ) -> None: ...
    def append(self, ls: LineString) -> None: ...
    def clear(self) -> None: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, arg: int) -> LineString: ...
    def __iter__(self) -> Iterator[LineString]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setitem__(self, idx: int, ls: LineString) -> None: ...

class MultiPoint:
    points: list[Point]  # _BaseModelView[Point]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, points: collections.abc.Sequence[Point] = ...
    ) -> None: ...
    def append(self, pt: Point) -> None: ...
    def clear(self) -> None: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, arg: int) -> Point: ...
    def __iter__(self) -> Iterator[Point]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setitem__(self, idx: int, pt: Point) -> None: ...

class MultiPolygon:
    polygons: list[Polygon]  # _BaseModelView[Polygon]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, polygons: collections.abc.Sequence[Polygon] = ...
    ) -> None: ...
    def append(self, poly: Polygon) -> None: ...
    def clear(self) -> None: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, index: int) -> Polygon: ...
    def __iter__(self) -> Iterator[Polygon]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setitem__(self, index: int, item: Polygon) -> None: ...

class Point:
    lat: float
    lon: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, lon: float = ..., lat: float = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...

class Polygon:
    inners: list[Ring]  # _BaseModelView[Ring]
    outer: Ring
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, exterior: Ring, interiors: collections.abc.Sequence[Ring] = ...
    ) -> None: ...
    def append(self, ring: Ring) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Ring:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, lon: NDArray1DFloat64, lat: NDArray1DFloat64
    ) -> None: ...
    def append(self, point: Point) -> None: ...
    def clear(self) -> None: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, idx: int) -> Point: ...
    def __iter__(self) -> Iterator[Point]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setitem__(self, idx: int, point: Point) -> None: ...

class Segment:
    a: Point
    b: Point
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, a: tuple[float, float], b: tuple[float, float]) -> None: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, idx: int) -> Point: ...
    def __iter__(self) -> Iterator[Point]: ...
    def __len__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setitem__(self, idx: int, point: Point) -> None: ...

class Spheroid:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, semi_major_axis: float, flattening: float) -> None: ...
    def authalic_radius(self) -> float: ...
    def axis_ratio(self) -> float: ...
    def equatorial_circumference(
        self, semi_major_axis: bool = ...
    ) -> float: ...
    def equatorial_radius_of_curvature(self) -> float: ...
    def first_eccentricity_squared(self) -> float: ...
    def geocentric_radius(self, lat: float) -> float: ...
    def linear_eccentricity(self) -> float: ...
    def mean_radius(self) -> float: ...
    def polar_radius_of_curvature(self) -> float: ...
    def second_eccentricity_squared(self) -> float: ...
    def semi_minor_axis(self) -> float: ...
    def volumetric_radius(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def flattening(self) -> float: ...
    @property
    def semi_major_axis(self) -> float: ...

class _BaseModelView(Generic[_ConceptElement]):
    def append(self, item: _ConceptElement) -> None: ...
    def clear(self) -> None: ...
    def __getitem__(self, index: int) -> _ConceptElement: ...
    def __iter__(self) -> Iterator[_ConceptElement]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, index: int, item: _ConceptElement) -> None: ...
