from typing import overload
import enum

from . import Box, Point, Segment, Spheroid, _Concept

ANDOYER: Strategy
KARNEY: Strategy
THOMAS: Strategy
VINCENTY: Strategy

def area(
    geometry: _Concept,
    spheroid: Spheroid | None = None,
    strategy: Strategy = VINCENTY,
) -> float: ...
def centroid(geometry: Box | Segment) -> Point: ...
def azimuth(
    geometry: _Concept,
    spheroid: Spheroid | None = None,
    strategy: Strategy = VINCENTY,
) -> float: ...
def is_empty(geometry: _Concept) -> bool: ...
def is_simple(geometry: _Concept) -> bool: ...
@overload
def is_valid(geometry: _Concept, return_reason: bool) -> tuple[bool, str]: ...
@overload
def is_valid(geometry: _Concept) -> bool: ...

class Strategy(enum.Enum):
    ANDOYER = ...
    KARNEY = ...
    THOMAS = ...
    VINCENTY = ...
