from typing import overload

from . import MultiPolygon, Point, _Concept

def area(
    geometry: _Concept,
) -> float: ...
def azimuth(
    point1: Point,
    point2: Point,
) -> float: ...
def buffer(
    geometry: _Concept,
    distance_strategy: DistanceSymmetric | DistanceAsymmetric,
    join_strategy: JoinRound | JoinMiter,
    end_strategy: EndRound | EndFlat,
    point_strategy: PointCircle | PointSquare,
) -> MultiPolygon: ...
def centroid(geometry: _Concept) -> Point: ...
def is_empty(geometry: _Concept) -> bool: ...
def is_simple(geometry: _Concept) -> bool: ...
@overload
def is_valid(geometry: _Concept, return_reason: bool) -> tuple[bool, str]: ...
@overload
def is_valid(geometry: _Concept) -> bool: ...

class DistanceAsymmetric:
    def __init__(self, distance_left: float, distance_right: float) -> None: ...

class DistanceSymmetric:
    def __init__(self, buffer_distance: float) -> None: ...

class EndFlat:
    def __init__(self) -> None: ...

class EndRound:
    def __init__(self, points_per_circle: int = ...) -> None: ...

class JoinMiter:
    def __init__(self, miter_limit: float = ...) -> None: ...

class JoinRound:
    def __init__(self, points_per_circle: int = ...) -> None: ...

class PointCircle:
    def __init__(self, points_per_circle: int = ...) -> None: ...

class PointSquare:
    def __init__(self) -> None: ...
